UVVM/UVVM

bitvis_vip_uart/src/uart_bfm_pkg.vhd

For instance trying to send data(15 downto 8) with uart_transmit will fail.
The length of the vector is compared against config.num_data_bits in line 192 and ends in a failure if they are different, so looping just the range should be fine.

[VIP UART] Supports transmitting vectors with lowest index not at zero

---

bitvis_vip_axilite/src/axilite_bfm_pkg.vhd

Small fix to allow for a clean transcript while using AXI-lite BFM

Fix check_value & check_value_in_range calls in axilite_bfm

---

bitvis_vip_scoreboard/src/generic_sb_pkg.vhd

This will remove warning from vcom:
(vcom-1515) Prefix of predefined attribute "length" is function call "to_string".

Removed questa compile warning (vcom-1515)

---

bitvis_vip_uart/src/uart_bfm_pkg.vhd

The UART BFM transmit procedure was always waiting for one bit period in the parity slot, even when parity was disabled. This commit fixes the extra wait issue.

Remove wait cycle in UART BFM when UART parity is set to PARITY_NONE

---

bitvis_vip_axi/src/axi_bfm_pkg.vhd

In Riviera-PRO 2020.04 the build fails with
```
```
This fixes the mentioned inconsistencies and the build succeeds.

fix inconsistencies between declaration and body

---

bitvis_irqc/script/ghdl_compile_all_and_simulate.sh
bitvis_uart/script/ghdl_compile_all_and_simulate.sh
bitvis_vip_uart/script/ghdl_compile_all_and_simulate.sh

in GHDL calls reversed the order of arguments '--std=08 -frelaxed-rules' to make them compatible with GHDL 1.0, issue #137

GHDL 1.0 compatibility fix

---

bitvis_vip_axistream/src/transaction_pkg.vhd
bitvis_vip_axistream/src/vvc_methods_pkg.vhd

When writing a DUT model I needed to have access to the actually transmitted data length of the Axistream master VVC. Thus I added it to the vvc_transaction_info.
Please review if this makes sense, or show me a better way how to solve this. I might have missed something in the VVC as I'm very new to UVVM.

Axistream: Add data_length from VVC command to transaction_info

---

uvvm_vvc_framework/src/ti_protected_types_pkg.vhd

The comparison with vvc_id.name was always false, it should only compare for the valid length name.

Ti protected types pkg update

---

uvvm_vvc_framework/src_target_dependent/td_vvc_framework_common_methods_pkg.vhd

The default argument for t_channel made the method and the override
without t_channel ambigous when only using the required parameters.

Remove default t_channel arg

---

bitvis_vip_axistream/src/axistream_bfm_pkg.vhd
uvvm_util/src/adaptations_pkg.vhd

When debugging axistream transaction it is very helpful to be able to look at the entire received frame. Using ID_PACKET_DATA for this purpose is too verbose in my opinion.

axistream_receive: Add logging of frames

---

bitvis_vip_axistream/src/axistream_bfm_pkg.vhd

When running with large frames the to_string(data_array) would use up
all available memory and crash modelsim.

Fix performance issue with frame logging.

---

MAKE_SUPPORT.md
bitvis_irqc/script/Makefile
bitvis_uart/script/Makefile
script/Makefile_template
script/example.mk
script/examples.mk
script/multisim.mk
script/vcd2gtkw.sh

My make-support branch adds a handful of makefiles and a supporting shell script to the script directories of UVVM. These allow users trying UVVM for the first time to simulate the examples and view results as a waveform with a single make command. This depends on a correctly installed simulator (GHDL, NVC, ModelSim or Questa), and precompiled UVVM libraries. Windows users will need MSYS2 to run make. 
Here's a screenshot from my Windows PC:

Make support

---

uvvm_util/src/methods_pkg.vhd

Ref issue #173. This new overload for check_stable also specifies the value that the target shall have during the stable period. 
I took the liberty of changing the proposed function name from await_stable_value to check_stable, as this is more descriptive of the functionality.

check_stable with specified value

---

bitvis_vip_axilite/src/axilite_vvc.vhd

Added a delta cycle delay at the start of the read and write channel executors in the AXILITE VVC to allow the constructor to finish.

Fixes issue #181

---

vhdl_ls.toml

I am working on a VHDL language server (https://github.com/VHDL-LS/rust_hdl) that I think could be useful to you when developing UVVM.
It is able to parse and type check the entire UVVM code base and provides goto definition/declaration and find references.
The `vhdl_ls.toml` configuration file that provides the library mapping to VHDL-LS is provided by this PR,
The easiest way to try is to install the VSCode extension: https://marketplace.visualstudio.com/items?itemName=hbohlin.vhdl-ls
The language server is a 100% static binary that is installed automatically by the extension and works out of the box on Windows and Linux.
Since it is a language server (https://microsoft.github.io/language-server-protocol/) is will work in emacs and vim as well if you prefer those instead of VSCode.

Add VHDL-LS language server configuration file

---

.github/workflows/test-ghdl.yml
.github/workflows/test-nvc.yml
GETTING_STARTED.md
bitvis_irqc/README.TXT
bitvis_irqc/script/.gitignore
bitvis_irqc/script/compile_all_and_simulate.sh
bitvis_uart/README.TXT
bitvis_uart/script/.gitignore
bitvis_uart/script/compile_all_and_simulate.sh
script/.gitignore
script/compile_all.sh
script/multisim.sh
uvvm_util/script/.gitignore
uvvm_util/script/compile_src.sh

Shell scripts to improve the "first contact" experience with UVVM. Associated documentation updates and .gitignore files.
A first time user can now navigate to the script subdirectory of a demo and run a shell script to compile and simulate the demo with GHDL, NVC or ModelSim etc. The script also supports Xilinx XSim but of (as of version 2022.2) this still does not support VHDL-2008 well enough.

Additional shell scripts

---

bitvis_vip_axi/src/axi_vvc.vhd

Run the following minimal example simulation after having compiled UVVM and VVCs from the latest release: https://gist.github.com/am9417/9a24f9b84b32fa780ee4387f95342aba#file-axi_vvc_tb-vhd
The simulation configures an AXI VVC instance where the command queue (and the result queue) has a size of 1000 elements and a warning threshold at 950 elements. Then, 1000 write commands are added into the command queue simultaneously by issuing an `axi_write` commands, and the simulation finishes after a nanosecond. I would assume that the simulation would pass with only a warning raised after there are 950 elements in the queue.
However, the following TB_ERROR is raised, and the test won't pass:
> 'add() into generic queue (of size 150) when full'
which does not make sense as the queues should have …

Bug: Generic GC_CMD_QUEUE_COUNT_MAX in AXI VVC does not update sizes of command queues

---

bitvis_vip_spec_cov/script/run_spec_cov.py

`bitvis_vip_spec_cov/script/run_spec_cov.py` allows cleaning the partial coverage files only in the directory where the script was executed at. Sometimes it's quite clumsy to change the directory first and then executing the script with `--clean`.
Added support for giving the directory as a parameter for supporting running the script from another directory.

Support for giving directory-to-be-cleaned with a parameter in Spec Cov VIP's python script

---

bitvis_vip_uart/src/uart_bfm_pkg.vhd
bitvis_vip_uart/src/uart_rx_vvc.vhd
bitvis_vip_uart/src/uart_tx_vvc.vhd

The value of the **v_num_data_bits** variable is not updated when the configuration of the VIP UART instance is changed.
This is already solved in **UVVM_3_BETA**. However, it would be good to integrate this fix into the UVVM as well.
Also removed the constraint from the parameter in the **odd_parity()** function to support different data widths.
BR

Fix for updating v_num_data_bits when configuration changes

---

bitvis_vip_axi/src/axi_vvc.vhd

The current change removes all warning messages on the vip_axi module
Below previous warning messages:
```
#########################################
#########################################
```

Removing extra warning at simulation time when using QuestaSim

---

doc/source/utility_library.rst

Added the missing arguments to the `await_value()` in the Utility Library documentation for std_logic_vector, unsigned, and signed types.

fix(docs):await_value arguments

---

uvvm_util/src/string_methods_pkg.vhd

string_methods_pkg.to_string() overload for t_positive_vector type

---

bitvis_vip_uart/src/vvc_methods_pkg.vhd

Removed unnecessary use clause causing the documentation to not be correct
Closes #256

Removed unnecessary use clause in vvc_methods_pkg.vhd for the UART VVC

---

bitvis_uart/script/ghdl_compile_all_and_simulate.sh

The vvc_sb_pkg-files in bitvis_vip_uart and bitvis_vip_sbi were missing in the ghdl compilation-script. This caused compilation to fail.

Added missing vvc_sb_pkg-statements

---

bitvis_vip_axi/src/axi_vvc.vhd
bitvis_vip_axilite/src/axilite_channel_handler_pkg.vhd
bitvis_vip_axistream/src/axistream_bfm_pkg.vhd
bitvis_vip_axistream/src/vvc_methods_pkg.vhd
bitvis_vip_scoreboard/src/generic_sb_support_pkg.vhd
bitvis_vip_wishbone/src/wishbone_bfm_pkg.vhd
uvvm_util/src/methods_pkg.vhd

Various checking commands in VVCs caused log messages with message ID ID_POS_ACK on the default message id panel, meaning that turning off the message in the VVC message id panel didn't stop the messages from coming. I changed the checks to use the correct message id panel and also change the message ID to ID_NEVER because I don't believe we want ID_POS_ACK messages from these checks.
closes #260

Fixed unwanted messages from VVCs

---

uvvm_util/src/func_cov_pkg.vhd
uvvm_util/src/generic_queue_pkg.vhd
uvvm_util/src/methods_pkg.vhd
uvvm_util/src/protected_types_pkg.vhd
uvvm_util/src/rand_pkg.vhd
uvvm_util/src/string_methods_pkg.vhd
uvvm_vvc_framework/src/ti_generic_queue_pkg.vhd
uvvm_vvc_framework/src/ti_vvc_framework_support_pkg.vhd
uvvm_vvc_framework/src_target_dependent/td_vvc_entity_support_pkg.vhd

Fixed all of the warnings that seemed unsafe from #268. 
Some of the warnings are not actually unsafe. For instance multiple places where access types are generated with the new keyword with a specific range. However, this still causes the warning about "unknown direction"
closes #268

Added some missing normalizations of subprogram parameters

---

doc/source/utility_library.rst

Added the missing arguments to the await_value() table in the Utility Library documentation.

fix(docs): await_value arguments table
